version: '3'
services:
    ahoy:
        build: .
        image: ahoy
        command: ahoy
        expose:
            - "1234"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - ahoy
